# Generated by Django 5.1.3 on 2025-03-08 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('planificacion', 'Planificación'), ('diseno', 'Diseño'), ('construccion', 'Construcción'), ('terminado', 'Terminado'), ('pausado', 'Pausado')], default='planificacion', max_length=20)),
                ('ubicacion', models.CharField(max_length=255)),
                ('metros_cuadrados', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='Funcion.cliente')),
            ],
        ),
    ]
